### ISSUE TITLE
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'

### ISSUE THREAD

**Issue by genemiller** [chriskelly/LifeFinances#143]
I assume issues #141 and #142  occurred because of the port 5000 issue on **MacOS 12.X**.
So I decided to switch to **Windows 10**, where the following errors occurred:
```
C:\Users\gene\Documents\GitHub\LifeFinances>python --version
Python 3.11.4

C:\Users\gene\Documents\GitHub\LifeFinances>python app.py
Traceback (most recent call last):
  File "C:\Users\gene\Documents\GitHub\LifeFinances\app.py", line 15, in <module>
    socketio = SocketIO(app)
               ^^^^^^^^^^^^^
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_socketio\__init__.py", line 187, in __init__
    self.init_app(app, **kwargs)
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_socketio\__init__.py", line 243, in init_app
    self.server = socketio.Server(**self.server_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\socketio\server.py", line 134, in __init__
    self.eio = self._engineio_server_class()(**engineio_options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\engineio\server.py", line 138, in __init__
    self._async = importlib.import_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\engineio\async_drivers\eventlet.py", line 3, in <module>
    from eventlet.green.threading import Thread, Event
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\eventlet\green\socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\eventlet\green\_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\eventlet\greenio\__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\eventlet\greenio\base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\eventlet\timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
    ^^^^^^^^^^^^^^^
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
```

**Comment by genemiller** [comment]
NOTE: I got the same errors when I ran `app.py` on a different Windows 10 machine.

**Comment by genemiller** [comment]
Downgrading to Python 3.9.13 on Windows. eliminated the error `cannot set 'is_timeout' attribute` 
However, I am now getting the same failures on Windows and as on MacOS 12
Specifically 2 cases continued to fail:
1. with `__main__` section commented-out:
-- `app.py` terminated with no output
2. with comments removed from `__main__`, and default port 5000 specified:
-- 1st browser tab with opened ERR 403
-- 2nd browser tab with opened ERR 404

**Comment by chriskelly** [comment]
Hi Gene, I'll reply to #141 and #142 here.
Thanks for checking out the project, though your timing is unfortunate. I'm currently in the middle of a massive [refactoring](https://github.com/chriskelly/LifeFinances/tree/major_refactor). The refactoring will be moving the project to a Docker container which will ideally get rid of these platform/version specific issues. 

The main issue you're running into is that I haven't updated the Readme. I recently moved the Flask routes to the `routes.py` file, so that's the file you should be running, not the app.py. Put all the files back the way they were, then run `python routes.py` and the GUI should pop up just fine. Let me know if you run into any other issues.

I'm sorry for the frustration and that the main branch is not in a better state at the moment. It actually took me a while to debug your issue as I had forgotten I'd moved the __main__ function and was trying to run the project as described in the Readme as well. If you do like what you see though and are familiar with Python, happy to have help on the refactoring branch!

**Comment by chriskelly** [comment]
Also, let me know if you're still having issues with port 5000. My MacBook is older and doesn't have the Airplay Receiver option, so I'm not sure if that part is resolved.

**Comment by genemiller** [comment]
Thank you.,

The application is coming up okay on my MacOS 12.
Disabling Airplay Receiver was enough to free up port 5000.

And downgrading from Python 3.11 to Python 3.9 made this issue go away: [TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'](https://github.com/chriskelly/LifeFinances/issues/143)

Thank you for sharing this interesting application.
I intend to study the underlying data model and method for compounding volatile investment growth.

I see that http://127.0.0.1:5000/parameters has lots of options for mid-career users. Since my wife and I are retired I will try exercising some of the features most useful to us (e.g. annuities).

Will keep you posted.
